branch-defaults:
  main:
    environment: churros
    group_suffix: null
environment-defaults:
  churros:
    branch: null
    repository: null
global:
  application_name: CHURROS_2021
  branch: null
  default_ec2_keyname: ricardo
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
