name: CI Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        SERVER_LOG=$(mktemp)
        coverage run -m src.server >& $SERVER_LOG &
        serverPID=$!
        sleep 3
        pytest tests/
        kill $serverPID
        cat $SERVER_LOG
        sleep 3
    - name: Generate coverage report
      run: |
        coverage report
        coverage html
      env:
        COVERAGE_REPORT: ${{ github.workspace }}/htmlcov/index.html
      if: always()
      run: echo "coverage-report=$COVERAGE_REPORT" >>$GITHUB_OUTPUT
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ${{ steps.pytest.outputs.coverage-report }}
    # - name: Run pylint
    #   run: |
    #     find . -type f -name "*.py" | egrep -v ".git/*" | xargs pylint
    # - name: Run mypy
    #   run: |
    #     find . -type f -name "*.py" | egrep -v ".git/*" | xargs mypy