name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        SERVER_LOG=$(mktemp)
        coverage run -m src.server >& $SERVER_LOG &
        pytest tests/
        kill -SIGINT %1
        cat $SERVER_LOG
        coverage report
        coverage html
      env:
        CI: true
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov/
    - name: Run pylint
      run: |
        find . -type f -name "*.py" | egrep -v ".git/*" | xargs pylint
    - name: Run mypy
      run: |
        find . -type f -name "*.py" | egrep -v ".git/*" | xargs mypy
